JOURNAL_TYPES_BULLET = 1
JOURNAL_TYPES_FOOD = 2
JOURNAL_TYPES_TRAVEL = 3
JOURNAL_TYPES_SPORT = 4
JOURNAL_TYPES = (
    (JOURNAL_TYPES_BULLET, 'bullet'),
    (JOURNAL_TYPES_FOOD, 'food'),
    (JOURNAL_TYPES_TRAVEL, 'travel'),
    (JOURNAL_TYPES_SPORT, 'sport'),
)
